# This workflow installs the latest version of Terraform CLI and configures the Terraform CLI configuration file
# with an API token for Terraform Cloud (app.terraform.io). On pull request events, this workflow will run
# `terraform init`, `terraform fmt`, and `terraform plan` (speculative plan via Terraform Cloud). On push events
# to the main branch, `terraform apply` will be executed.
#
# Documentation for `hashicorp/setup-terraform` is located here: https://github.com/hashicorp/setup-terraform
#
# To use this workflow, you will need to complete the following setup steps.
#
# 1. Create a `main.tf` file in the root of this repository with the `remote` backend and one or more resources defined.
#   Example `main.tf`:
#     # The configuration for the `remote` backend.
#     terraform {
#       backend "remote" {
#         # The name of your Terraform Cloud organization.
#         organization = "example-organization"
#
#         # The name of the Terraform Cloud workspace to store Terraform state files in.
#         workspaces {
#           name = "example-workspace"
#         }
#       }
#     }
#
#     # An example resource that does nothing.
#     resource "null_resource" "example" {
#       triggers = {
#         value = "A example resource that does nothing!"
#       }
#     }
#
#
# 2. Generate a Terraform Cloud user API token and store it as a GitHub secret (e.g. TF_API_TOKEN) on this repository.
#   Documentation:
#     - https://www.terraform.io/docs/cloud/users-teams-organizations/api-tokens.html
#     - https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets
#
# 3. Reference the GitHub secret in step using the `hashicorp/setup-terraform` GitHub Action.
#   Example:
#     - name: Setup Terraform
#       uses: hashicorp/setup-terraform@v1
#       with:
#         cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

name: "Terraform"

env:
  LU_FILE: ./Chatroom/Offensive-Intents.lu  

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  # terraform:
  #   runs-on: ubuntu-latest
  #   outputs:
  #     webapp_name: ${{ steps.tf_output.outputs.url }} # map step output to job output
  #   steps:
  #     - id: tf_output
  #       name: send url to other job
  #       run: echo "::set-output name=url::https://google.com"
  # job2:
  #   runs-on: ubuntu-latest
  #   needs: terraform
  #   steps:
  #     - run: echo ${{ needs.terraform.outputs.webapp_name }} # grab job output here
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    outputs:
      webapp_name: ${{ steps.tf_output.outputs.webapp }}
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v2
      # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false #We need this to get the output
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
      - name: Terraform Init
        run: terraform init
      # Checks that all Terraform configuration files adhere to a canonical format
      # - name: Terraform Format
      #   run: terraform fmt -check
      # Generates an execution plan for Terraform
      - name: Terraform Plan
        run: terraform plan
        # On push to main, build or change infrastructure according to Terraform configuration files
        # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve
      - id: tf_output
        run: echo "::set-output name=webapp::$(terraform output -raw app_service_name)"
  luis:
    name: "LUIS model"
    needs: [terraform]
    runs-on: ubuntu-latest
    steps:
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.3
        with:
          versionSpec: '5.2.x'
      - name: Use GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.3
      - name: luisAppVersion env
        run: echo "::set-env name=luisAppVersion::$GitVersion_SemVer"
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Get LUIS authoring key
        run: |
          keya=$(az cognitiveservices account keys list --name $AzureLuisAuthoringResourceName --resource-group $AzureResourceGroup --query "key1" | xargs)
          echo "::set-env name=LUISAuthoringKey::$keya"
          echo "::add-mask::$keya"
      - name: Get LUIS prediction key
        run: |
          keyp=$(az cognitiveservices account keys list --name $AzureLuisPredictionResourceName --resource-group $AzureResourceGroup --query "key1" | xargs)
          echo "::set-env name=LUISPredictionKey::$keyp"
          echo "::add-mask::$keyp"
      - name: Get LUIS authoring endpoint
        run: |
          az cognitiveservices account show --name $AzureLuisAuthoringResourceName --resource-group $AzureResourceGroup --query "properties.endpoint" | \
          xargs -I {} echo "::set-env name=luisAuthoringEndpoint::{}"
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Bypass botframework-cli telemetry prompts, enable telemetry collection - set to false to disable telemetry collection
        run: echo "::set-env name=BF_CLI_TELEMETRY::true"
      - name: Install @microsoft/botframework-cli
        run: |
          npm i -g @microsoft/botframework-cli
      - name: Ludown to LUIS model
        run: bf luis:convert -i $LU_FILE -o ./model.json --name 'LUIS CI pipeline - ${{ github.run_id }}' --versionid $luisAppVersion
  deployment:
    name: "Deploy code"
    needs: [terraform, luis]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "3.1.x" # SDK Version to use; x will use the latest version of the 3.1 channel
      - run: |
          dotnet restore
          dotnet build ./Chatroom -c Release
          dotnet publish ./Chatroom -c Release -o './webapp'
      # - name: Check the value of the terraform output
      #   run: |
      #     echo ${{ needs.terraform.outputs.webapp_name }}
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ needs.terraform.outputs.webapp_name }} #This should be an output from Terraform job
          package: ./webapp
